'use strict';
const C=MomCore,$=id=>document.getElementById(id),key='momcare_v5',uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2),categories={casa:'Casa',filhos:'Filhos',eu:'Pessoal'},days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
let state=C.empty(),storageError=false,category='all',noteFilter='all',timerMinutes=5,timerRemaining=300,timerEnd=null,timerInterval=null,lastReminderSync='',lastDay=C.day(),alerted=new Set();
try{const raw=localStorage.getItem(key);if(raw){const data=JSON.parse(raw);if(!C.valid(data))throw Error();state=data;}else{const old=localStorage.getItem('momcare_ultra_v4');if(old)state=C.migrate(JSON.parse(old));}}catch{storageError=true;}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),4000);}
function save(next){try{if(storageError){const original=localStorage.getItem(key);if(original)localStorage.setItem(key+'_recuperacao',original);storageError=false;}localStorage.setItem(key,JSON.stringify(next));state=next;render();return true;}catch{toast('Não foi possível salvar. Faça um backup e tente novamente.');return false;}}
function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;}
function nav(tab){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===tab));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));window.scrollTo(0,0);}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>nav(b.dataset.tab));$('settings').onclick=()=>nav('config');$('home-pause').onclick=()=>nav('care');
function empty(container,title,text){const e=node('div','','empty');e.append(node('strong',title),node('span',text));container.append(e);}
function dateText(date){return new Date(date+'T12:00:00').toLocaleDateString('pt-BR',{day:'numeric',month:'short',year:'numeric'});}
function taskCard(t,date,manage=false){const isDone=C.done(t,date),row=node('div','',`task ${isDone?'done':''} ${t.priority?'important':''}`);if(!manage){const tick=node('button',isDone?'✓':'','tick');tick.setAttribute('aria-label',(isDone?'Reabrir ':'Concluir ')+t.title);tick.disabled=date>C.day();tick.onclick=()=>{const tasks=state.tasks.map(x=>x.id===t.id?{...x,doneDates:isDone?x.doneDates.filter(d=>d!==date):[...x.doneDates,date]}:x);if(save({...state,tasks})&&!isDone)toast('Atividade concluída. Um passo de cada vez.');};row.append(tick);}const info=node('div','','info');info.append(node('div',t.title,'task-title'),node('small',(t.priority?'Importante · ':'')+categories[t.category]+(t.days.length?' · '+(t.days.length===7?'Todos os dias':t.days.map(d=>days[d].slice(0,3)).join(', ')):manage?' · '+dateText(t.date):'')));const edit=node('button','⋯','edit');edit.setAttribute('aria-label','Editar '+t.title);edit.onclick=()=>openTask(t);row.append(info,node('span',t.time,'time'),edit);return row;}
function render(){const today=C.day(),list=state.tasks.filter(t=>C.occurs(t,today)).sort((a,b)=>a.time.localeCompare(b.time)),completed=list.filter(t=>C.done(t,today)).length;const h=new Date().getHours();$('today-label').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'}).toUpperCase();$('greeting').textContent=state.name?(h<12?'Bom dia, ':h<18?'Boa tarde, ':'Boa noite, ')+state.name+'.':'Seu dia, com mais leveza.';$('today-progress').textContent=completed+' de '+list.length;$('progress-bar').style.width=(list.length?completed/list.length*100:0)+'%';$('progress-message').textContent=!list.length?'Seu dia ainda está em branco. Adicione uma atividade.':completed===list.length?'Você concluiu sua rotina de hoje. Reserve um tempo para você.':(list.length-completed)+' atividades para fazer, no seu ritmo.';$('next-task').replaceChildren();const next=list.find(t=>!C.done(t,today));if(next)$('next-task').append(taskCard(next,today));const waterCount=state.water[today]||0;$('water-total').textContent=waterCount+(waterCount===1?' copo':' copos');$('water-minus').disabled=!(state.water[today]>0);$('memory-count').textContent=state.notes.filter(n=>n.memory).length;renderRoutine();renderNotes();const week=C.week(),counts=week.map(date=>state.tasks.filter(t=>C.done(t,date)).length);$('week-done').textContent=counts.reduce((a,b)=>a+b,0);$('week-memory').textContent=state.notes.filter(n=>n.memory&&week.includes(n.date)).length;$('week-chart').replaceChildren();const max=Math.max(1,...counts);week.forEach((date,i)=>{const col=node('div','','chart-col');col.title=dateText(date)+': '+counts[i]+' concluídas';col.setAttribute('aria-label',col.title);const bar=node('div','','bar');bar.style.height=Math.max(3,counts[i]/max*75)+'px';col.append(bar,node('small',new Date(date+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short'})));$('week-chart').append(col);});syncReminders();}
function renderRoutine(){const date=$('routine-date').value||C.day(),tasks=state.tasks.filter(t=>C.occurs(t,date)&&(category==='all'||category===t.category)),show=$('show-done').checked;tasks.sort((a,b)=>Number(C.done(a,date))-Number(C.done(b,date))||a.time.localeCompare(b.time));$('routine-count').textContent=tasks.length+' atividades';$('task-list').replaceChildren();const visible=tasks.filter(t=>show||!C.done(t,date));if(!visible.length)empty($('task-list'),'Um pouco de espaço no seu dia','Adicione uma atividade ou escolha outra data.');else visible.forEach(t=>$('task-list').append(taskCard(t,date)));$('all-tasks').replaceChildren();state.tasks.slice().sort((a,b)=>a.title.localeCompare(b.title)).forEach(t=>$('all-tasks').append(taskCard(t,date,true)));if(!state.tasks.length)empty($('all-tasks'),'Tudo começa com um passo','Suas atividades vão aparecer aqui.');}
function renderNotes(){const q=$('note-search').value.toLocaleLowerCase('pt-BR'),notes=state.notes.filter(n=>(noteFilter==='all'||(noteFilter==='memory'?n.memory:!n.memory))&&n.content.toLocaleLowerCase('pt-BR').includes(q)).slice().sort((a,b)=>b.date.localeCompare(a.date));$('notes-list').replaceChildren();if(!notes.length){empty($('notes-list'),'Guarde o que faz sentido para você','Uma frase, um lembrete ou um momento especial.');return;}for(const n of notes){const el=node('article','','note '+(n.memory?'memory':'')),top=node('div','','section-head'),edit=node('button','Editar ↗','edit');edit.onclick=()=>openNote(n);edit.setAttribute('aria-label','Editar anotação');top.append(node('span',n.memory?'✧ MEMÓRIA ESPECIAL':'ANOTAÇÃO','label'),edit);el.append(top,node('p',n.content),node('small',dateText(n.date)));$('notes-list').append(el);}}
$('routine-date').value=C.day();$('routine-date').onchange=renderRoutine;$('show-done').onchange=renderRoutine;$('category-filter').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.category;$('category-filter').querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));renderRoutine();});$('note-search').oninput=renderNotes;$('note-filter').querySelectorAll('button').forEach(b=>b.onclick=()=>{noteFilter=b.dataset.noteFilter;$('note-filter').querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));renderNotes();});
const tf=$('task-form');function openTask(t){tf.reset();$('task-error').textContent='';tf.elements.id.value=t?t.id:'';tf.elements.title.value=t?t.title:'';tf.elements.date.value=t?t.date:$('routine-date').value;tf.elements.time.value=t?t.time:'09:00';tf.elements.category.value=t?t.category:'casa';tf.elements.priority.checked=t? t.priority:false;tf.querySelectorAll('[name=days]').forEach(x=>x.checked=t?t.days.includes(Number(x.value)):false);$('delete-task').hidden=!t;$('task-title').textContent=t?'Editar atividade':'Nova atividade';$('task-dialog').showModal();}
$('add-task').onclick=()=>openTask();tf.querySelectorAll('[name=days]').forEach(x=>x.setAttribute('aria-label',days[Number(x.value)]));
tf.onsubmit=e=>{e.preventDefault();const f=tf.elements,old=state.tasks.find(t=>t.id===f.id.value),t={id:f.id.value||uid(),title:f.title.value.trim(),date:f.date.value,time:f.time.value,category:f.category.value,priority:f.priority.checked,days:[...tf.querySelectorAll('[name=days]:checked')].map(x=>Number(x.value)),doneDates:old?old.doneDates:[]};if(!C.task(t)){$('task-error').textContent='Preencha uma atividade, data e horário válidos.';return;}const tasks=old?state.tasks.map(x=>x.id===t.id?t:x):[...state.tasks,t];if(save({...state,tasks})){$('task-dialog').close();toast('Atividade salva');}};
$('delete-task').onclick=()=>{if(confirm('Excluir esta atividade e seu histórico de conclusões?')&&save({...state,tasks:state.tasks.filter(t=>t.id!==tf.elements.id.value)}))$('task-dialog').close();};
const nf=$('note-form');function openNote(n,memory=false){nf.reset();nf.elements.id.value=n?n.id:'';nf.elements.content.value=n?n.content:'';nf.elements.date.value=n?n.date:C.day();nf.elements.memory.checked=n?n.memory:memory;$('note-error').textContent='';$('delete-note').hidden=!n;$('note-title').textContent=n?'Editar anotação':memory?'Guardar uma memória':'Nova anotação';$('note-dialog').showModal();}
$('new-memory').onclick=()=>openNote(null,true);$('add-note').onclick=()=>openNote();nf.onsubmit=e=>{e.preventDefault();const f=nf.elements,n={id:f.id.value||uid(),content:f.content.value.trim(),date:f.date.value,memory:f.memory.checked};if(!C.note(n)||n.date>C.day()){$('note-error').textContent='Escreva sua anotação e escolha uma data até hoje.';return;}const notes=f.id.value?state.notes.map(x=>x.id===n.id?n:x):[n,...state.notes];if(save({...state,notes})){$('note-dialog').close();toast('Anotação salva');}};$('delete-note').onclick=()=>{if(confirm('Excluir esta anotação?')&&save({...state,notes:state.notes.filter(n=>n.id!==nf.elements.id.value)}))$('note-dialog').close();};document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function water(delta){const date=C.day(),count=Math.min(100,Math.max(0,(state.water[date]||0)+delta));save({...state,water:{...state.water,[date]:count}});}$('water-plus').onclick=()=>water(1);$('water-minus').onclick=()=>water(-1);
function displayTimer(){const m=Math.floor(timerRemaining/60),s=timerRemaining%60;$('timer').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');$('timer-toggle').textContent=timerEnd?'Pausar':timerRemaining===0?'Começar de novo':timerRemaining<timerMinutes*60?'Continuar pausa':'Começar pausa';document.querySelector('.pause-card').classList.toggle('running',!!timerEnd);}
function tickTimer(){if(!timerEnd)return;timerRemaining=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));if(timerRemaining===0){clearInterval(timerInterval);timerInterval=null;timerEnd=null;toast('Sua pausa terminou. Volte no seu ritmo.');}displayTimer();}
function resetTimer(){clearInterval(timerInterval);timerInterval=null;timerEnd=null;timerRemaining=timerMinutes*60;displayTimer();}
$('timer-toggle').onclick=()=>{if(timerEnd){tickTimer();timerEnd=null;clearInterval(timerInterval);timerInterval=null;displayTimer();}else{if(timerRemaining===0)timerRemaining=timerMinutes*60;timerEnd=Date.now()+timerRemaining*1000;timerInterval=setInterval(tickTimer,250);displayTimer();}};$('timer-reset').onclick=resetTimer;document.querySelectorAll('[data-minutes]').forEach(b=>b.onclick=()=>{timerMinutes=Number(b.dataset.minutes);document.querySelectorAll('[data-minutes]').forEach(x=>x.classList.toggle('selected',x===b));resetTimer();});document.addEventListener('visibilitychange',()=>{if(!document.hidden){tickTimer();render();}});
$('profile-form').elements.name.value=state.name;$('profile-form').onsubmit=e=>{e.preventDefault();if(save({...state,name:e.target.elements.name.value.trim()}))toast('Nome atualizado');};
function syncReminders(){if(window.Android&&Android.syncReminders){const text=JSON.stringify(state.tasks);if(text!==lastReminderSync){Android.syncReminders(text);lastReminderSync=text;}}}
window.momReminderStatus=s=>{$('enable-notifications').textContent=s?'Notificações ativadas · desativar':'Ativar notificações';};$('enable-notifications').onclick=()=>{if(window.Android&&Android.toggleReminders)Android.toggleReminders();else toast('Notificações com o app fechado estão disponíveis no APK Android.');};
function importData(text){try{const d=JSON.parse(text),next=d.version===5?d:C.migrate(d);if(!C.valid(next))throw Error();if(!confirm('Restaurar este backup? As atividades e notas atuais serão substituídas.'))return;if(save(next)){$('profile-form').elements.name.value=state.name;toast('Backup restaurado');}}catch{toast('Backup inválido. Nenhum dado foi alterado.');}}
function exportData(){const text=JSON.stringify(state,null,2);if(window.Android){Android.saveBackup(text);return;}const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='MomCare-backup-'+C.day()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
window.momImport=importData;window.momNotice=toast;$('export').onclick=exportData;$('import').onclick=()=>window.Android?Android.openBackup():$('import-file').click();$('import-file').onchange=async e=>{const f=e.target.files[0];if(f){if(f.size>5000000)toast('O backup deve ter até 5 MB');else importData(await f.text());}e.target.value='';};
setInterval(()=>{const today=C.day();if(today!==lastDay){lastDay=today;$('routine-date').value=today;lastReminderSync='';alerted.clear();render();}if(!window.Android){const now=new Date(),time=String(now.getHours()).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0');for(const t of state.tasks){const k=t.id+today;if(C.occurs(t,today)&&!C.done(t,today)&&t.time===time&&!alerted.has(k)){alerted.add(k);toast('Hora de: '+t.title);}}}},15000);
if(!window.Android){$('reminder-description').textContent='Nesta versão web, os lembretes aparecem enquanto o app está aberto. No APK Android, você pode ativar notificações locais.';}
render();if(window.Android&&Android.reminderStatus)Android.reminderStatus();if(storageError)toast('Não foi possível ler os dados salvos. Os dados originais foram preservados.');
if('serviceWorker' in navigator&&!window.Android)navigator.serviceWorker.register('./sw.js').catch(()=>{});
